# Generated by Django 4.0.2 on 2022-03-03 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import endterm.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endterm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='users',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=endterm.models.user_directory_path),
        ),
        migrations.CreateModel(
            name='userPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=800, null=True)),
                ('mediaFile1', models.FileField(blank=True, null=True, upload_to=endterm.models.user_post_path)),
                ('mediaFile2', models.FileField(blank=True, null=True, upload_to=endterm.models.user_post_path)),
                ('mediaFile3', models.FileField(blank=True, null=True, upload_to=endterm.models.user_post_path)),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='endterm.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='publicChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=800, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publicChat_user', to='endterm.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='friendReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to=settings.AUTH_USER_MODEL)),
                ('ToUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
