# Generated by Django 4.0.2 on 2022-03-03 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endterm', '0003_alter_friendlist_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendreq',
            name='FromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendreq',
            name='ToUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
