# Generated by Django 4.0.2 on 2022-03-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endterm', '0007_friends_delete_friendlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='posttime',
            field=models.TimeField(auto_now=True),
        ),
    ]
