# Generated by Django 4.0.2 on 2022-03-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endterm', '0008_userpost_posttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicchat',
            old_name='user_id',
            new_name='user',
        ),
    ]
