# Generated by Django 4.0.2 on 2022-03-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endterm', '0010_alter_publicchat_user_alter_userpost_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='chat_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
